### ISSUE TITLE
Problem Vehicle

### ISSUE THREAD

**Issue by stevenbreak** [nassTman/nass_tebexstore#12]
Hello i have probleme
i am in QB

![Screenshot_3](https://user-images.githubusercontent.com/89803997/189477963-2bc2ca5a-e5bf-49e3-acd5-d4c8fbe9389a.png)

i try to resolve the probleme
i change in config type car in type vehicle
no error but vehicle not spwan

**Comment by najeetpie** [comment]
Change the vehicle type from varchar to longtext

**Comment by stevenbreak** [comment]
Hello where i change it ?
