### ISSUE TITLE
Can we feature this in a Video

### ISSUE THREAD

**Issue by liam-wiltshire** [nassTman/nass_tebexstore#4]
Hey @nassTman,

We're loving the work you've done here to make it far easier to support in-game deliverables.

Would you be ok with us doing a video featuring this on our YouTube channel? https://www.youtube.com/channel/UCG00mHuHnO5imfIOzikqu8A?app=desktop

Thanks,

Liam

**Comment by najeetpie** [comment]
@liam-wiltshire, Of course you can. Glad to see my script has been useful to the community. Hoping to test out qb and get both frameworks supported.

**Comment by liam-wiltshire** [comment]
Awesome - we'd love to explore other ways we can support you with this as well - I'd be great if you could ping an email to support@tebex.io and ask them to assign it to me so we can discuss! 😁

**Comment by najeetpie** [comment]
Sure thing, will do that right now.
